# Generated by Django 4.1 on 2022-08-08 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_imagemessage_sended_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemessage',
            old_name='reciever',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='textmessage',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
